apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-1gi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
