apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
