apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-1gi
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: cluster-storage
  resources:
    requests:
      storage: 1Gi
