apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: cluster-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
