apiVersion: v1
kind: Pod
metadata:
  name: express-nodejs-pod
  labels:
    app: express-nodejs
spec:
  containers:
    - name: frontend
      image: afzaalahmadzeeshan/express-nodejs:latest
      resources:
        limits:
          memory: 256Mi
          cpu: 250m
      ports:
        - containerPort: 5000
          hostPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: express-nodejs-service
  labels:
    type: LoadBalancer
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: express-nodejs-pod
