apiVersion: v1
kind: Service
metadata:
  name: express-nodejs-service
  labels:
    type: LoadBalancer
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: express-nodejs-pod
